<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%--
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at
   
         http://www.apache.org/licenses/LICENSE-2.0
   
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Multibox Example</title>
<link rel="stylesheet" type="text/css" href="<c:url value="/css/example.css"/>" />
</head>
<body>
<p><jsp:include page="/jsp/topNav.jsp" flush="true" /></p>
	<spring:url value="index.jsp" var="indexUrl"></spring:url>
	<spring:url value="/images/return.gif" var="returnUrl"></spring:url>
	<a href="${indexUrl}"><img src="${returnUrl}" height="24"
		width="24" alt="Return to examples page" class="icon" /></a>
<h1>Multibox Example</h1>
<hr noshade="noshade"/>
<form:form action="processMultibox.do" modelAttribute="multiboxForm" method="POST">
	<h2>1. Simple multibox tags</h2>
  <p>Checkboxes are statically defined in the JSP.<br />
     Initially selected values are defined in the 'prepare' Action.</p>
	<form:checkbox path="fruits" value="Strawberry"/>Strawberry<br />
	<form:checkbox path="fruits" value="Apple"/>Apple<br />
	<form:checkbox path="fruits" value="Orange"/>Orange<br />
	<form:checkbox path="fruits" value="Pear"/>Pear<br />
	<form:checkbox path="fruits" value="Mango"/>Mango<br />
	<form:checkbox path="fruits" value="Banana"/>Banana<br />
	<form:checkbox path="fruits" value="Pineapple"/>Pineapple<br />

	<h2>2. Multibox tags generated from an array</h2>
	<p>The checkboxes are generated by iterating over a String array containing color names.<br />
	   Initially selected values are defined in the 'prepare' Action.</p>
	<c:forEach items="${colors}" var="color">
		<form:checkbox path="colors" value="${color}"/>${color}<br />
	</c:forEach>
	<hr />
		<p>
			<button type="submit">
				<spring:message code="button.submit" />
			</button>
			<button type="submit" name="org.springbridge.action.CANCEL">
				<spring:message code="button.cancel" />
			</button>
			<button type="reset">
				<spring:message code="button.reset" />
			</button>
		</p>
</form:form>

</body>
</html>